version: "3.8"

services:
  immich-server:
    image: ax-immich-server:latest
    build:
      context: ../server
    restart: unless-stopped

  # immich-machine-learning:
  #   image: ax-immich-ml:latest
  #   build:
  #     context: ../machine-learning
  #   volumes:
  #       - /usr/lib/axcl:/usr/lib/axcl:ro
  #   environment:
  #     - LD_LIBRARY_PATH=/usr/lib/axcl:$LD_LIBRARY_PATH
  #   devices:
  #     - /dev/ax0:/dev/ax0
  #   restart: unless-stopped
    
  # immich-machine-learning:
  #   deploy:
  #     replicas: 0
